server:
  port: 8899
spring:
  application:
    name: Ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/e_commerce?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 200309
  data:
    ## redis配置
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 10000ms
      username:
      password:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  ## 上传文件配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ##线程池配置
  task:
    execution:
      pool:
        core-size: 8        # 核心线程数(默认)
        max-size: 20        # 最大线程数
        queue-capacity: 50  # 队列大小
        keep-alive: 60s     # 线程空闲时间(默认)
      thread-name-prefix: task- # 线程名前缀
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启自动驼峰命名
jwt:
  key: ligg #加密密钥

token:
  expire: 6 #过期时间

##文件配置
file:
  image:
    base-path: resources/image # 用相对路径(相对于项目运行目录)
    relative-path: /api/image # 图片访问的相对路径前缀(用于返回给前端)

api:
  base-url: "http://localhost:8899" #填写后端的ip或域名(用于拼接完整的资源访问路径)
